In [35]:
import tensorflow as tf
input=[16.0]

In [36]:
#Linear Activation Function, f(x)=x
tf.keras.activations.linear(input)

[16.0]

In [37]:
#Sigmoid Activation Function, f(x)=1/(1+e^-x)
print(tf.keras.activations.sigmoid(input))

tf.Tensor([0.9999999], shape=(1,), dtype=float32)


In [38]:
#Hyperbolic Tangent Activation Function, f(x)=tanh(x)
print(tf.keras.activations.tanh(input))

tf.Tensor([1.], shape=(1,), dtype=float32)


In [39]:
#Rectified Linear Unit (ReLU) Activation Function, f(x)=max(0,x)
print(tf.keras.activations.relu(input))

tf.Tensor([16.], shape=(1,), dtype=float32)


In [48]:
#Leaky ReLU activation function
print(tf.keras.layers.LeakyReLU(alpha=0.3)(tf.constant(-60.0)))

tf.Tensor(-18.0, shape=(), dtype=float32)


In [ ]:
#Softmax Activation Function
print(tf.keras.activations.softmax(tf.constant([1.0, 2.0, 3.0, 60.0])))

tf.Tensor([2.3802667e-26 6.4702359e-26 1.7587924e-25 1.0000000e+00], shape=(4,), dtype=float32)
