In [33]:
#Tensor operation
import tensorflow as tf


In [34]:
#create tensors
tensor_a=tf.constant([[1,2],[3,4]])
tensor_b=tf.constant([[5,6],[7,8]])

In [35]:
#Arithmetic operation


In [36]:
tf.add(tensor_a,tensor_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

In [37]:
tf.subtract(tensor_a,tensor_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]], dtype=int32)>

In [38]:
tf.multiply(tensor_a,tensor_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [39]:
tf.divide(tensor_a,tensor_b)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])>

In [40]:
tf.square(tensor_a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [41]:
tf.square(tensor_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 36],
       [49, 64]], dtype=int32)>

In [42]:
#tf.sqrt(tensor_a) it does not support int32 value, it only sopport float value
tf.sqrt(tf.cast(tensor_a, tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [1.7320508, 2.       ]], dtype=float32)>

In [43]:
#exponential, it only work for exponential
tf.exp(tf.cast(tensor_a, tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.7182817,  7.389056 ],
       [20.085537 , 54.59815  ]], dtype=float32)>

In [44]:
#logarithmic
tf.math.log(tf.cast(tensor_a, tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.       , 0.6931472],
       [1.0986123, 1.3862944]], dtype=float32)>

In [45]:
#Reduction Operation

In [46]:
tf.reduce_sum(tensor_a)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [47]:
tf.reduce_mean(tensor_a)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [48]:
tf.reduce_max(tensor_b)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [49]:
#Matrix Operation

In [50]:
#multiplication
tf.matmul(tensor_a,tensor_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [51]:
#Transportation
tf.transpose(tensor_a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [52]:

#Matrix Inverse
tf.linalg.inv(tf.cast(tensor_a, tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [62]:
#Operation which only work for float are:
#tf.sqrt()
#tf.exp()
#tf.math.log()
#tf.linalg.inv

In [54]:
#indexing and slicing
tensor_a[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [55]:
tensor_a[0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [56]:
tensor_a[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [57]:
tensor_a[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [58]:
tensor_a[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [59]:
#Broadcasting
tensor_c=tf.constant([[1,2]])
tensor_a+tensor_c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [4, 6]], dtype=int32)>

In [60]:
tensor_a*tensor_c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 8]], dtype=int32)>

In [61]:
tensor_a-tensor_c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [2, 2]], dtype=int32)>