In [1]:
import tensorflow as tf

In [2]:
#Create a constant Variable
constant_tensor=tf.constant([1,2,3,4,5,6])
constant_tensor

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
#variable: You can change value of tensor after creating variable


In [5]:

tf.random.normal(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.97601795, -2.3344069 ,  0.9267341 ],
       [-1.0231696 ,  0.9104872 , -0.59432775],
       [-1.1525564 , -1.617397  , -0.8186818 ]], dtype=float32)>

In [6]:
initial_value=tf.random.normal(shape=(3,3))
variable_tensor=tf.Variable(initial_value)
variable_tensor

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.0626944e-03, -1.1033828e+00,  1.2110455e+00],
       [ 1.8174129e+00,  1.5247437e-01, -3.7905893e-01],
       [-1.7855750e-01,  2.0802212e+00, -4.9902478e-01]], dtype=float32)>

In [7]:
new_value=tf.random.normal(shape=(3,3))
variable_tensor.assign(new_value)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[-1.2654314 ,  0.42322707,  1.0252522 ],
       [ 3.148815  , -1.6121726 , -0.5526703 ],
       [-1.3516316 , -1.4930431 ,  0.80901355]], dtype=float32)>

In [10]:
#Placeholder: Used to fit data
x=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
y=tf.sqrt(x)
y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)>